version: '3.5'
services:
  db:
    image: postgres:14
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

volumes:
  postgres: